# Generated by Django 3.0.5 on 2020-04-28 12:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='text',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='published_date',
        ),
        migrations.AddField(
            model_name='blog',
            name='subheading',
            field=models.CharField(max_length=200)
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100)
        ),
        migrations.AddField(
            model_name='blog',
            name='photo_caption',
            field=models.TextField(default='Imaages By owner'),
        ),
        migrations.AddField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 12, 36, 18, 287401, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
