# Generated by Django 3.0.5 on 2020-04-28 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200428_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='subheading',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
