# Generated by Django 3.0.5 on 2020-04-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200428_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blockquote',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
