# Generated by Django 3.0.5 on 2020-04-29 06:50

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200428_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='publish_date',
            new_name='publish',
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
