# Generated by Django 3.0.5 on 2020-04-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200429_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='publish',
            new_name='publish_date',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='status',
        ),
    ]
