# Generated by Django 3.0.5 on 2020-04-30 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_userprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
    ]
